# b = ["张三","lisi","wangwu"]
# for i in b:
#     print("我的名字叫%s" %i)
# a = [30,28,77,16,98]

c = ("张三",20,1.75)
print(type(c))
print("我的名字是%s,我的年龄是%d,我的身高是%.2f" %c)
# a.sort()
# print(a)
# print(b.index("张三"))
# b[1] = "李四"
# print(b[1])
# b.append("zhangsan")
# print(b)
# b.insert(1,"liyi")
# print(b)
# b.extend(a)
# print(b)
# # b.clear()
# # print(b)
# b.remove("liyi")
# print(b)
# b.pop(2)
# print(b)
# print(b.count("张三"))
# a.sort(reverse=True)
# print(a)
# a.reverse()
# print(a)